export const GET_NETWORK_INFO_BEGIN = 'GET_NETWORK_INFO_BEGIN';
export const GET_NETWORK_INFO_SUCCESS = 'GET_NETWORK_INFO_SUCCESS';
export const GET_NETWORK_INFO_FAILURE = 'GET_NETWORK_INFO_FAILURE';

export const GET_BLOCKCHAIN_INFO_BEGIN = 'GET_BLOCKCHAIN_INFO_BEGIN';
export const GET_BLOCKCHAIN_INFO_SUCCESS = 'GET_BLOCKCHAIN_INFO_SUCCESS';
export const GET_BLOCKCHAIN_INFO_FAILURE = 'GET_BLOCKCHAIN_INFO_FAILURE';

export const SET_DEFAULT_ACCOUNT_SUCCESS = 'SET_DEFAULT_ACCOUNT_SUCCESS';
export const SET_DEFAULT_ACCOUNT_FAILURE = 'SET_DEFAULT_ACCOUNT_FAILURE';
