export const GET_NETWORK_INFO_BEGIN = 'GET_NETWORK_INFO_BEGIN';
export const GET_NETWORK_INFO_SUCCESS = 'GET_NETWORK_INFO_SUCCESS';
export const GET_NETWORK_INFO_FAILURE = 'GET_NETWORK_INFO_FAILURE';

export const GET_BLOCKCHAIN_INFO_BEGIN = 'GET_BLOCKCHAIN_INFO_BEGIN';
export const GET_BLOCKCHAIN_INFO_SUCCESS = 'GET_BLOCKCHAIN_INFO_SUCCESS';
export const GET_BLOCKCHAIN_INFO_FAILURE = 'GET_BLOCKCHAIN_INFO_FAILURE';

export const SET_DEFAULT_ACCOUNT_SUCCESS = 'SET_DEFAULT_ACCOUNT_SUCCESS';
export const SET_DEFAULT_ACCOUNT_FAILURE = 'SET_DEFAULT_ACCOUNT_FAILURE';

export const ON_NAME_CHANGE = 'ON_NAME_CHANGE';
export const ON_BUYER_ADDRESS_CHANGE = 'ON_BUYER_ADDRESS_CHANGE';
export const ON_RFP_CHANGE = 'ON_RFP_CHANGE';
export const ON_RFP_DEADLINE_CHANGE = 'ON_RFP_DEADLINE_CHANGE';
export const ON_BID_TYPE_CHANGE = 'ON_BID_TYPE_CHANGE';
export const ON_SELLERS_ADDRESSES_CHANGE = 'ON_SELLERS_ADDRESSES_CHANGE';

export const ON_SEND_PO_BEGIN = 'ON_SEND_PO_BEGIN';
export const ON_SEND_PO_SUCCESS = 'ON_SEND_PO_SUCCESS';
export const ON_SEND_PO_FAILURE = 'ON_SEND_PO_FAILURE';

export const CLEAR_PO = 'CLEAR_PO';

export const GET_POS_BEGIN = 'GET_POS_BEGIN';
export const GET_POS_SUCCESS = 'GET_POS_SUCCESS';
export const GET_POS_FAILURE = 'GET_POS_FAILURE';
