export const GET_NETWORK_INFO_BEGIN = 'GET_NETWORK_INFO_BEGIN';
export const GET_NETWORK_INFO_SUCCESS = 'GET_NETWORK_INFO_SUCCESS';
export const GET_NETWORK_INFO_FAILURE = 'GET_NETWORK_INFO_FAILURE';

export const GET_BLOCKCHAIN_INFO_BEGIN = 'GET_BLOCKCHAIN_INFO_BEGIN';
export const GET_BLOCKCHAIN_INFO_SUCCESS = 'GET_BLOCKCHAIN_INFO_SUCCESS';
export const GET_BLOCKCHAIN_INFO_FAILURE = 'GET_BLOCKCHAIN_INFO_FAILURE';
